<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BesoinRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BesoinRepository extends BaseRepository
{
    public function __construct($manager, $classMetadata)
    {
        parent::__construct($manager, $classMetadata, 'b');
    }
}
