<?php

namespace AppBundle\Repository;


/**
 * ListeKeySuccessRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ListeKeySuccessRepository extends BaseRepository
{
    public function __construct($manager, $classMetadata)
    {
        parent::__construct($manager, $classMetadata, 'lk');
    }
}
