<?php

namespace AppBundle\Repository;


/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    public function __construct($manager, $classMetadata)
    {
        parent::__construct($manager, $classMetadata, 'u');
    }
}
