services:
    api_provider.webservice_user_provider:
        class: AppBundle\Security\WebServiceUserProvider
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

    api_extractor.auth_token:
        class: AppBundle\Security\AuthTokenExtractor
        arguments: ['', 'Authorization']

    api_handler.authentication_success:
        class: AppBundle\Security\AuthenticationSuccessHandler
        arguments: ['@jms_serializer', '@event_dispatcher', '@doctrine.orm.entity_manager']

    api_handler.authentication_failure:
        class: AppBundle\Security\AuthenticationFailureHandler

    api_authenticator.api_key:
        class: AppBundle\Security\ApiKeyAuthenticator
        arguments: ['@event_dispatcher', '@api_extractor.auth_token']